import type { CurveTemplate, DistractorStrategy, RFunc, Tier } from "@/types";

const PI = Math.PI;
const TWO_PI = 2 * PI;
const FOUR_PI = 4 * PI;
const SIX_PI = 6 * PI;

// ---------------------------------------------------------------------------
// 100 hand-picked polar curves — every shape is visually distinct
// ---------------------------------------------------------------------------

export const curves: CurveTemplate[] = [
  // ===== 1. CIRCLE =====
  {
    id: "circle",
    name: "Circle",
    family: "circle",
    expression: "r = 3",
    rFunc: () => 3,
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["param-tweak", "family-swap"],
    params: { a: 3 },
  },

  // ===== 2–5. CARDIOIDS =====
  {
    id: "cardioid-cos-plus",
    name: "Cardioid (1+cosθ)",
    family: "cardioid",
    expression: "r = 1 + cos θ",
    rFunc: (t) => 1 + Math.cos(t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["trig-swap", "sign-flip", "param-tweak"],
    params: { a: 1, sign: 1 },
  },
  {
    id: "cardioid-sin-plus",
    name: "Cardioid (1+sinθ)",
    family: "cardioid",
    expression: "r = 1 + sin θ",
    rFunc: (t) => 1 + Math.sin(t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["trig-swap", "sign-flip", "param-tweak"],
    params: { a: 1, sign: 1 },
  },
  {
    id: "cardioid-cos-minus",
    name: "Cardioid (1−cosθ)",
    family: "cardioid",
    expression: "r = 1 - cos θ",
    rFunc: (t) => 1 - Math.cos(t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["trig-swap", "sign-flip", "param-tweak"],
    params: { a: 1, sign: -1 },
  },
  {
    id: "cardioid-sin-minus",
    name: "Cardioid (1−sinθ)",
    family: "cardioid",
    expression: "r = 1 - sin θ",
    rFunc: (t) => 1 - Math.sin(t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["trig-swap", "sign-flip", "param-tweak"],
    params: { a: 1, sign: -1 },
  },

  // ===== 6–13. LIMAÇONS =====
  {
    id: "limacon-dimpled-cos",
    name: "Limaçon dimpled (3+2cosθ)",
    family: "limacon-no-loop",
    expression: "r = 3 + 2cos θ",
    rFunc: (t) => 3 + 2 * Math.cos(t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["trig-swap", "param-tweak", "family-swap"],
    params: { a: 3, b: 2 },
  },
  {
    id: "limacon-dimpled-sin",
    name: "Limaçon dimpled (3+2sinθ)",
    family: "limacon-no-loop",
    expression: "r = 3 + 2sin θ",
    rFunc: (t) => 3 + 2 * Math.sin(t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["trig-swap", "param-tweak", "family-swap"],
    params: { a: 3, b: 2 },
  },
  {
    id: "limacon-convex",
    name: "Limaçon convex (4+cosθ)",
    family: "limacon-no-loop",
    expression: "r = 4 + cos θ",
    rFunc: (t) => 4 + Math.cos(t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["trig-swap", "param-tweak", "family-swap"],
    params: { a: 4, b: 1 },
  },
  {
    id: "limacon-loop-cos",
    name: "Limaçon with loop (1+2cosθ)",
    family: "limacon-loop",
    expression: "r = 1 + 2cos θ",
    rFunc: (t) => 1 + 2 * Math.cos(t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["trig-swap", "sign-flip", "param-tweak", "ratio-flip"],
    params: { a: 1, b: 2 },
  },
  {
    id: "limacon-loop-sin",
    name: "Limaçon with loop (1+2sinθ)",
    family: "limacon-loop",
    expression: "r = 1 + 2sin θ",
    rFunc: (t) => 1 + 2 * Math.sin(t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["trig-swap", "sign-flip", "param-tweak", "ratio-flip"],
    params: { a: 1, b: 2 },
  },
  {
    id: "limacon-loop-cos-minus",
    name: "Limaçon with loop (1−2cosθ)",
    family: "limacon-loop",
    expression: "r = 1 - 2cos θ",
    rFunc: (t) => 1 - 2 * Math.cos(t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["trig-swap", "sign-flip", "param-tweak", "ratio-flip"],
    params: { a: 1, b: -2 },
  },
  {
    id: "limacon-loop-big",
    name: "Limaçon with loop (2+3cosθ)",
    family: "limacon-loop",
    expression: "r = 2 + 3cos θ",
    rFunc: (t) => 2 + 3 * Math.cos(t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["trig-swap", "sign-flip", "param-tweak", "ratio-flip"],
    params: { a: 2, b: 3 },
  },
  {
    id: "limacon-loop-sin-minus",
    name: "Limaçon with loop (2−3sinθ)",
    family: "limacon-loop",
    expression: "r = 2 - 3sin θ",
    rFunc: (t) => 2 - 3 * Math.sin(t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["trig-swap", "sign-flip", "param-tweak", "ratio-flip"],
    params: { a: 2, b: -3 },
  },

  // ===== 14–29. ROSES (integer petals) =====
  {
    id: "rose-sin2",
    name: "Rose sin(2θ)",
    family: "rose-even",
    expression: "r = sin(2θ)",
    rFunc: (t) => Math.sin(2 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["trig-swap", "frequency-shift", "param-tweak"],
    params: { a: 1, n: 2 },
  },
  {
    id: "rose-cos2",
    name: "Rose cos(2θ)",
    family: "rose-even",
    expression: "r = cos(2θ)",
    rFunc: (t) => Math.cos(2 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["trig-swap", "frequency-shift", "param-tweak"],
    params: { a: 1, n: 2 },
  },
  {
    id: "rose-sin3",
    name: "Rose sin(3θ)",
    family: "rose-odd",
    expression: "r = sin(3θ)",
    rFunc: (t) => Math.sin(3 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["trig-swap", "frequency-shift", "param-tweak"],
    params: { a: 1, n: 3 },
  },
  {
    id: "rose-cos3",
    name: "Rose cos(3θ)",
    family: "rose-odd",
    expression: "r = cos(3θ)",
    rFunc: (t) => Math.cos(3 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["trig-swap", "frequency-shift", "param-tweak"],
    params: { a: 1, n: 3 },
  },
  {
    id: "rose-sin4",
    name: "Rose sin(4θ)",
    family: "rose-even",
    expression: "r = sin(4θ)",
    rFunc: (t) => Math.sin(4 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["trig-swap", "frequency-shift", "param-tweak"],
    params: { a: 1, n: 4 },
  },
  {
    id: "rose-cos4",
    name: "Rose cos(4θ)",
    family: "rose-even",
    expression: "r = cos(4θ)",
    rFunc: (t) => Math.cos(4 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["trig-swap", "frequency-shift", "param-tweak"],
    params: { a: 1, n: 4 },
  },
  {
    id: "rose-sin5",
    name: "Rose sin(5θ)",
    family: "rose-odd",
    expression: "r = sin(5θ)",
    rFunc: (t) => Math.sin(5 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["trig-swap", "frequency-shift", "param-tweak"],
    params: { a: 1, n: 5 },
  },
  {
    id: "rose-cos5",
    name: "Rose cos(5θ)",
    family: "rose-odd",
    expression: "r = cos(5θ)",
    rFunc: (t) => Math.cos(5 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["trig-swap", "frequency-shift", "param-tweak"],
    params: { a: 1, n: 5 },
  },
  {
    id: "rose-sin6",
    name: "Rose sin(6θ)",
    family: "rose-even",
    expression: "r = sin(6θ)",
    rFunc: (t) => Math.sin(6 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["trig-swap", "frequency-shift", "param-tweak"],
    params: { a: 1, n: 6 },
  },
  {
    id: "rose-cos7",
    name: "Rose cos(7θ)",
    family: "rose-odd",
    expression: "r = cos(7θ)",
    rFunc: (t) => Math.cos(7 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["trig-swap", "frequency-shift", "param-tweak"],
    params: { a: 1, n: 7 },
  },
  {
    id: "rose-sin8",
    name: "Rose sin(8θ)",
    family: "rose-even",
    expression: "r = sin(8θ)",
    rFunc: (t) => Math.sin(8 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["trig-swap", "frequency-shift", "param-tweak"],
    params: { a: 1, n: 8 },
  },
  {
    id: "rose-cos9",
    name: "Rose cos(9θ)",
    family: "rose-odd",
    expression: "r = cos(9θ)",
    rFunc: (t) => Math.cos(9 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["trig-swap", "frequency-shift", "param-tweak"],
    params: { a: 1, n: 9 },
  },
  {
    id: "rose-sin10",
    name: "Rose sin(10θ)",
    family: "rose-even",
    expression: "r = sin(10θ)",
    rFunc: (t) => Math.sin(10 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["trig-swap", "frequency-shift", "param-tweak"],
    params: { a: 1, n: 10 },
  },
  {
    id: "rose-2sin3",
    name: "Rose 2sin(3θ)",
    family: "rose-odd",
    expression: "r = 2sin(3θ)",
    rFunc: (t) => 2 * Math.sin(3 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["trig-swap", "frequency-shift", "param-tweak"],
    params: { a: 2, n: 3 },
  },
  {
    id: "rose-3cos2",
    name: "Rose 3cos(2θ)",
    family: "rose-even",
    expression: "r = 3cos(2θ)",
    rFunc: (t) => 3 * Math.cos(2 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["trig-swap", "frequency-shift", "param-tweak"],
    params: { a: 3, n: 2 },
  },

  // ===== 30–35. ROSES (rational frequency) =====
  {
    id: "rose-rat-2-3",
    name: "Rose cos(2θ/3)",
    family: "rose-rational",
    expression: "r = cos(2θ/3)",
    rFunc: (t) => Math.cos((2 / 3) * t),
    thetaRange: [0, 3 * TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "ratio-flip", "trig-swap"],
    params: { p: 2, q: 3 },
  },
  {
    id: "rose-rat-3-2",
    name: "Rose cos(3θ/2)",
    family: "rose-rational",
    expression: "r = cos(3θ/2)",
    rFunc: (t) => Math.cos((3 / 2) * t),
    thetaRange: [0, FOUR_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "ratio-flip", "trig-swap"],
    params: { p: 3, q: 2 },
  },
  {
    id: "rose-rat-5-3",
    name: "Rose sin(5θ/3)",
    family: "rose-rational",
    expression: "r = sin(5θ/3)",
    rFunc: (t) => Math.sin((5 / 3) * t),
    thetaRange: [0, 3 * TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "ratio-flip", "trig-swap"],
    params: { p: 5, q: 3 },
  },
  {
    id: "rose-rat-4-3",
    name: "Rose cos(4θ/3)",
    family: "rose-rational",
    expression: "r = cos(4θ/3)",
    rFunc: (t) => Math.cos((4 / 3) * t),
    thetaRange: [0, 3 * TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "ratio-flip", "trig-swap"],
    params: { p: 4, q: 3 },
  },
  {
    id: "rose-rat-3-4",
    name: "Rose sin(3θ/4)",
    family: "rose-rational",
    expression: "r = sin(3θ/4)",
    rFunc: (t) => Math.sin((3 / 4) * t),
    thetaRange: [0, 4 * TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "ratio-flip", "trig-swap"],
    params: { p: 3, q: 4 },
  },
  {
    id: "rose-rat-5-2",
    name: "Rose cos(5θ/2)",
    family: "rose-rational",
    expression: "r = cos(5θ/2)",
    rFunc: (t) => Math.cos((5 / 2) * t),
    thetaRange: [0, FOUR_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "ratio-flip", "trig-swap"],
    params: { p: 5, q: 2 },
  },

  // ===== 36–38. LEMNISCATES =====
  {
    id: "lemniscate-cos",
    name: "Lemniscate r²=4cos(2θ)",
    family: "lemniscate",
    expression: "r² = 4cos(2θ)",
    rFunc: { rSquared: true, func: (t) => 4 * Math.cos(2 * t) } as RFunc,
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["trig-swap", "sign-flip", "param-tweak"],
    params: { a: 2 },
  },
  {
    id: "lemniscate-sin",
    name: "Lemniscate r²=4sin(2θ)",
    family: "lemniscate",
    expression: "r² = 4sin(2θ)",
    rFunc: { rSquared: true, func: (t) => 4 * Math.sin(2 * t) } as RFunc,
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["trig-swap", "sign-flip", "param-tweak"],
    params: { a: 2 },
  },
  {
    id: "lemniscate-big",
    name: "Lemniscate r²=9cos(2θ)",
    family: "lemniscate",
    expression: "r² = 9cos(2θ)",
    rFunc: { rSquared: true, func: (t) => 9 * Math.cos(2 * t) } as RFunc,
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["trig-swap", "sign-flip", "param-tweak"],
    params: { a: 3 },
  },

  // ===== 39–44. SPIRALS =====
  {
    id: "archimedes-slow",
    name: "Archimedes spiral (0.5θ)",
    family: "archimedes",
    expression: "r = 0.5θ",
    rFunc: (t) => 0.5 * t,
    thetaRange: [0, SIX_PI],
    tier: 1,
    distractorStrategies: ["param-tweak", "family-swap"],
    params: { a: 0.5 },
  },
  {
    id: "archimedes-fast",
    name: "Archimedes spiral (θ)",
    family: "archimedes",
    expression: "r = θ",
    rFunc: (t) => t,
    thetaRange: [0, SIX_PI],
    tier: 1,
    distractorStrategies: ["param-tweak", "family-swap"],
    params: { a: 1 },
  },
  {
    id: "log-spiral-slow",
    name: "Log spiral (e^0.1θ)",
    family: "log-spiral",
    expression: "r = e^(0.1θ)",
    rFunc: (t) => Math.exp(0.1 * t),
    thetaRange: [0, SIX_PI],
    tier: 1,
    distractorStrategies: ["param-tweak", "family-swap"],
    params: { a: 1, b: 0.1 },
  },
  {
    id: "log-spiral-fast",
    name: "Log spiral (0.3·e^0.2θ)",
    family: "log-spiral",
    expression: "r = 0.3·e^(0.2θ)",
    rFunc: (t) => 0.3 * Math.exp(0.2 * t),
    thetaRange: [0, SIX_PI],
    tier: 1,
    distractorStrategies: ["param-tweak", "family-swap"],
    params: { a: 0.3, b: 0.2 },
  },
  {
    id: "fermat-spiral",
    name: "Fermat's spiral r²=4θ",
    family: "fermat",
    expression: "r² = 4θ",
    rFunc: { rSquared: true, func: (t) => 4 * t } as RFunc,
    thetaRange: [0, SIX_PI],
    tier: 1,
    distractorStrategies: ["param-tweak", "family-swap"],
    params: { a: 2 },
  },
  {
    id: "hyperbolic-spiral",
    name: "Hyperbolic spiral (2/θ)",
    family: "hyperbolic",
    expression: "r = 2/θ",
    rFunc: (t) => 2 / t,
    thetaRange: [0.1, SIX_PI],
    tier: 1,
    distractorStrategies: ["param-tweak", "family-swap"],
    params: { a: 2 },
  },

  // ===== 45–49. CONIC SECTIONS =====
  {
    id: "conic-ellipse",
    name: "Conic ellipse (e=0.5)",
    family: "conic",
    expression: "r = 2/(1 + 0.5cos θ)",
    rFunc: (t) => 2 / (1 + 0.5 * Math.cos(t)),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["param-tweak", "sign-flip", "family-swap"],
    params: { a: 2, e: 0.5 },
  },
  {
    id: "conic-parabola",
    name: "Conic parabola (e=1)",
    family: "conic",
    expression: "r = 2/(1 + cos θ)",
    rFunc: (t) => 2 / (1 + Math.cos(t)),
    thetaRange: [0.05, TWO_PI - 0.05],
    tier: 1,
    distractorStrategies: ["param-tweak", "sign-flip", "family-swap"],
    params: { a: 2, e: 1 },
  },
  {
    id: "conic-hyperbola",
    name: "Conic hyperbola (e=1.5)",
    family: "conic",
    expression: "r = 2/(1 + 1.5cos θ)",
    rFunc: (t) => 2 / (1 + 1.5 * Math.cos(t)),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["param-tweak", "sign-flip", "family-swap"],
    params: { a: 2, e: 1.5 },
  },
  {
    id: "conic-ellipse-sin",
    name: "Conic ellipse sin (e=0.3)",
    family: "conic",
    expression: "r = 3/(1 + 0.3sin θ)",
    rFunc: (t) => 3 / (1 + 0.3 * Math.sin(t)),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["param-tweak", "trig-swap", "family-swap"],
    params: { a: 3, e: 0.3 },
  },
  {
    id: "conic-near-circle",
    name: "Conic near-circle (e=0.8)",
    family: "conic",
    expression: "r = 1/(1 + 0.8cos θ)",
    rFunc: (t) => 1 / (1 + 0.8 * Math.cos(t)),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["param-tweak", "sign-flip", "family-swap"],
    params: { a: 1, e: 0.8 },
  },

  // ===== 50. BUTTERFLY =====
  {
    id: "butterfly",
    name: "Butterfly curve",
    family: "butterfly",
    expression: "r = e^sin(θ) - 2cos(4θ) + sin⁵((2θ-π)/24)",
    rFunc: (t) =>
      Math.exp(Math.sin(t)) -
      2 * Math.cos(4 * t) +
      Math.pow(Math.sin((2 * t - PI) / 24), 5),
    thetaRange: [0, 12 * PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "param-tweak"],
    params: {},
  },

  // ===== 51–58. LIMAÇON-ROSE HYBRIDS =====
  {
    id: "hybrid-1-2-3",
    name: "Hybrid 1+2sin(3θ)",
    family: "limacon-rose-hybrid",
    expression: "r = 1 + 2sin(3θ)",
    rFunc: (t) => 1 + 2 * Math.sin(3 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "param-tweak", "trig-swap"],
    params: { a: 1, b: 2, n: 3 },
  },
  {
    id: "hybrid-1-2-4",
    name: "Hybrid 1+2sin(4θ)",
    family: "limacon-rose-hybrid",
    expression: "r = 1 + 2sin(4θ)",
    rFunc: (t) => 1 + 2 * Math.sin(4 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "param-tweak", "trig-swap"],
    params: { a: 1, b: 2, n: 4 },
  },
  {
    id: "hybrid-2-3-2",
    name: "Hybrid 2+3sin(2θ)",
    family: "limacon-rose-hybrid",
    expression: "r = 2 + 3sin(2θ)",
    rFunc: (t) => 2 + 3 * Math.sin(2 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "param-tweak", "trig-swap"],
    params: { a: 2, b: 3, n: 2 },
  },
  {
    id: "hybrid-1-1-5",
    name: "Hybrid 1+sin(5θ)",
    family: "limacon-rose-hybrid",
    expression: "r = 1 + sin(5θ)",
    rFunc: (t) => 1 + Math.sin(5 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "param-tweak", "trig-swap"],
    params: { a: 1, b: 1, n: 5 },
  },
  {
    id: "hybrid-2-1-4",
    name: "Hybrid 2+cos(4θ)",
    family: "limacon-rose-hybrid",
    expression: "r = 2 + cos(4θ)",
    rFunc: (t) => 2 + Math.cos(4 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "param-tweak", "trig-swap"],
    params: { a: 2, b: 1, n: 4 },
  },
  {
    id: "hybrid-3-2-3",
    name: "Hybrid 3+2cos(3θ)",
    family: "limacon-rose-hybrid",
    expression: "r = 3 + 2cos(3θ)",
    rFunc: (t) => 3 + 2 * Math.cos(3 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "param-tweak", "trig-swap"],
    params: { a: 3, b: 2, n: 3 },
  },
  {
    id: "hybrid-1-3-6",
    name: "Hybrid 1+3sin(6θ)",
    family: "limacon-rose-hybrid",
    expression: "r = 1 + 3sin(6θ)",
    rFunc: (t) => 1 + 3 * Math.sin(6 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "param-tweak", "trig-swap"],
    params: { a: 1, b: 3, n: 6 },
  },
  {
    id: "hybrid-2-2-5",
    name: "Hybrid 2+2cos(5θ)",
    family: "limacon-rose-hybrid",
    expression: "r = 2 + 2cos(5θ)",
    rFunc: (t) => 2 + 2 * Math.cos(5 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "param-tweak", "trig-swap"],
    params: { a: 2, b: 2, n: 5 },
  },

  // ===== 59–68. COMPOUND ADDITIVE =====
  {
    id: "compound-cos2-sin3",
    name: "cos(2θ)+sin(3θ)",
    family: "compound",
    expression: "r = cos(2θ) + sin(3θ)",
    rFunc: (t) => Math.cos(2 * t) + Math.sin(3 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "trig-swap", "param-tweak"],
    params: { m: 2, n: 3 },
  },
  {
    id: "compound-cos3-sin5",
    name: "cos(3θ)+sin(5θ)",
    family: "compound",
    expression: "r = cos(3θ) + sin(5θ)",
    rFunc: (t) => Math.cos(3 * t) + Math.sin(5 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "trig-swap", "param-tweak"],
    params: { m: 3, n: 5 },
  },
  {
    id: "compound-cos1-sin2",
    name: "cos(θ)+sin(2θ)",
    family: "compound",
    expression: "r = cos(θ) + sin(2θ)",
    rFunc: (t) => Math.cos(t) + Math.sin(2 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "trig-swap", "param-tweak"],
    params: { m: 1, n: 2 },
  },
  {
    id: "compound-cos4-sin1",
    name: "cos(4θ)+sin(θ)",
    family: "compound",
    expression: "r = cos(4θ) + sin(θ)",
    rFunc: (t) => Math.cos(4 * t) + Math.sin(t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "trig-swap", "param-tweak"],
    params: { m: 4, n: 1 },
  },
  {
    id: "compound-sin2-sin3",
    name: "sin(2θ)+sin(3θ)",
    family: "compound",
    expression: "r = sin(2θ) + sin(3θ)",
    rFunc: (t) => Math.sin(2 * t) + Math.sin(3 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "trig-swap", "param-tweak"],
    params: { m: 2, n: 3 },
  },
  {
    id: "compound-2cos1-cos3",
    name: "2cos(θ)+cos(3θ)",
    family: "compound",
    expression: "r = 2cos(θ) + cos(3θ)",
    rFunc: (t) => 2 * Math.cos(t) + Math.cos(3 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "trig-swap", "param-tweak"],
    params: { m: 1, n: 3 },
  },
  {
    id: "compound-cos5-sin2",
    name: "cos(5θ)+sin(2θ)",
    family: "compound",
    expression: "r = cos(5θ) + sin(2θ)",
    rFunc: (t) => Math.cos(5 * t) + Math.sin(2 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "trig-swap", "param-tweak"],
    params: { m: 5, n: 2 },
  },
  {
    id: "compound-sin4-cos3",
    name: "sin(4θ)+cos(3θ)",
    family: "compound",
    expression: "r = sin(4θ) + cos(3θ)",
    rFunc: (t) => Math.sin(4 * t) + Math.cos(3 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "trig-swap", "param-tweak"],
    params: { m: 4, n: 3 },
  },
  {
    id: "compound-cos2-cos5",
    name: "cos(2θ)+cos(5θ)",
    family: "compound",
    expression: "r = cos(2θ) + cos(5θ)",
    rFunc: (t) => Math.cos(2 * t) + Math.cos(5 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "trig-swap", "param-tweak"],
    params: { m: 2, n: 5 },
  },
  {
    id: "compound-sin1-sin5",
    name: "sin(θ)+sin(5θ)",
    family: "compound",
    expression: "r = sin(θ) + sin(5θ)",
    rFunc: (t) => Math.sin(t) + Math.sin(5 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "trig-swap", "param-tweak"],
    params: { m: 1, n: 5 },
  },

  // ===== 69–74. PRODUCT CURVES =====
  {
    id: "product-cos1-cos2",
    name: "cos(θ)·cos(2θ)",
    family: "product",
    expression: "r = cos(θ)·cos(2θ)",
    rFunc: (t) => Math.cos(t) * Math.cos(2 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "trig-swap", "family-swap"],
    params: { m: 1, n: 2 },
  },
  {
    id: "product-sin1-sin3",
    name: "sin(θ)·sin(3θ)",
    family: "product",
    expression: "r = sin(θ)·sin(3θ)",
    rFunc: (t) => Math.sin(t) * Math.sin(3 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "trig-swap", "family-swap"],
    params: { m: 1, n: 3 },
  },
  {
    id: "product-cos1-sin2",
    name: "cos(θ)·sin(2θ)",
    family: "product",
    expression: "r = cos(θ)·sin(2θ)",
    rFunc: (t) => Math.cos(t) * Math.sin(2 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "trig-swap", "family-swap"],
    params: { m: 1, n: 2 },
  },
  {
    id: "product-sin2-cos3",
    name: "sin(2θ)·cos(3θ)",
    family: "product",
    expression: "r = sin(2θ)·cos(3θ)",
    rFunc: (t) => Math.sin(2 * t) * Math.cos(3 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "trig-swap", "family-swap"],
    params: { m: 2, n: 3 },
  },
  {
    id: "product-cos2-cos3",
    name: "cos(2θ)·cos(3θ)",
    family: "product",
    expression: "r = cos(2θ)·cos(3θ)",
    rFunc: (t) => Math.cos(2 * t) * Math.cos(3 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "trig-swap", "family-swap"],
    params: { m: 2, n: 3 },
  },
  {
    id: "product-sin2-sin5",
    name: "sin(2θ)·sin(5θ)",
    family: "product",
    expression: "r = sin(2θ)·sin(5θ)",
    rFunc: (t) => Math.sin(2 * t) * Math.sin(5 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "trig-swap", "family-swap"],
    params: { m: 2, n: 5 },
  },

  // ===== 75–81. MULTI-FREQUENCY / TRIPLE COMPOUND =====
  {
    id: "triple-sin123",
    name: "sin(θ)+sin(2θ)+sin(3θ)",
    family: "compound",
    expression: "r = sin(θ) + sin(2θ) + sin(3θ)",
    rFunc: (t) => Math.sin(t) + Math.sin(2 * t) + Math.sin(3 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "trig-swap"],
    params: { m: 1, n: 3 },
  },
  {
    id: "triple-cos123",
    name: "cos(θ)+cos(2θ)+cos(3θ)",
    family: "compound",
    expression: "r = cos(θ) + cos(2θ) + cos(3θ)",
    rFunc: (t) => Math.cos(t) + Math.cos(2 * t) + Math.cos(3 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "trig-swap"],
    params: { m: 1, n: 3 },
  },
  {
    id: "multi-2-sin-cos2",
    name: "2+sin(θ)+cos(2θ)",
    family: "compound",
    expression: "r = 2 + sin(θ) + cos(2θ)",
    rFunc: (t) => 2 + Math.sin(t) + Math.cos(2 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "trig-swap"],
    params: { m: 1, n: 2 },
  },
  {
    id: "multi-3-cos3-sin2",
    name: "3+cos(3θ)+sin(2θ)",
    family: "compound",
    expression: "r = 3 + cos(3θ) + sin(2θ)",
    rFunc: (t) => 3 + Math.cos(3 * t) + Math.sin(2 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "trig-swap"],
    params: { m: 3, n: 2 },
  },
  {
    id: "multi-cos135",
    name: "cos(θ)+cos(3θ)+cos(5θ)",
    family: "compound",
    expression: "r = cos(θ) + cos(3θ) + cos(5θ)",
    rFunc: (t) => Math.cos(t) + Math.cos(3 * t) + Math.cos(5 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "trig-swap"],
    params: { m: 1, n: 5 },
  },
  {
    id: "multi-sin246",
    name: "sin(2θ)+sin(4θ)+sin(6θ)",
    family: "compound",
    expression: "r = sin(2θ) + sin(4θ) + sin(6θ)",
    rFunc: (t) => Math.sin(2 * t) + Math.sin(4 * t) + Math.sin(6 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "trig-swap"],
    params: { m: 2, n: 6 },
  },
  {
    id: "multi-1-cos-sin3-cos5",
    name: "1+cos(θ)+sin(3θ)+cos(5θ)",
    family: "compound",
    expression: "r = 1 + cos(θ) + sin(3θ) + cos(5θ)",
    rFunc: (t) => 1 + Math.cos(t) + Math.sin(3 * t) + Math.cos(5 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "trig-swap"],
    params: { m: 1, n: 5 },
  },

  // ===== 82–85. COCHLEOID & SPECIAL =====
  {
    id: "cochleoid",
    name: "Cochleoid sin(θ)/θ",
    family: "cochleoid",
    expression: "r = sin(θ)/θ",
    rFunc: (t) => Math.sin(t) / t,
    thetaRange: [0.01, SIX_PI],
    tier: 1,
    distractorStrategies: ["param-tweak", "family-swap"],
    params: { a: 1 },
  },
  {
    id: "cissoid-like",
    name: "Cissoid-like curve",
    family: "exotic",
    expression: "r = 2sin(θ)tan(θ)",
    rFunc: (t) => {
      const c = Math.cos(t);
      if (Math.abs(c) < 0.01) return 0;
      return 2 * Math.sin(t) * Math.sin(t) / c;
    },
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["family-swap"],
    params: {},
  },
  {
    id: "half-freq-rose",
    name: "Rose sin(θ/2)",
    family: "rose-rational",
    expression: "r = sin(θ/2)",
    rFunc: (t) => Math.sin(t / 2),
    thetaRange: [0, FOUR_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "trig-swap"],
    params: { p: 1, q: 2 },
  },
  {
    id: "third-freq-rose",
    name: "Rose cos(θ/3)",
    family: "rose-rational",
    expression: "r = cos(θ/3)",
    rFunc: (t) => Math.cos(t / 3),
    thetaRange: [0, 3 * TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "trig-swap"],
    params: { p: 1, q: 3 },
  },

  // ===== 86–93. EXOTIC / UNUSUAL =====
  {
    id: "heart",
    name: "Heart curve",
    family: "exotic",
    expression: "r = 2 - 2sin(θ) + sin(θ)√|cos(θ)|/(sin(θ)+1.4)",
    rFunc: (t) =>
      2 - 2 * Math.sin(t) +
      (Math.sin(t) * Math.sqrt(Math.abs(Math.cos(t)))) / (Math.sin(t) + 1.4),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["family-swap"],
    params: {},
  },
  {
    id: "four-leaf-product",
    name: "Four-leaf cos²(2θ)",
    family: "exotic",
    expression: "r = cos²(2θ)",
    rFunc: (t) => Math.pow(Math.cos(2 * t), 2),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "family-swap"],
    params: {},
  },
  {
    id: "peanut",
    name: "Peanut curve",
    family: "exotic",
    expression: "r² = cos(2θ) + 2",
    rFunc: { rSquared: true, func: (t) => Math.cos(2 * t) + 2 } as RFunc,
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["family-swap"],
    params: {},
  },
  {
    id: "clover",
    name: "Clover (sin²(2θ)+cos(4θ))",
    family: "exotic",
    expression: "r = sin²(2θ) + cos(4θ)",
    rFunc: (t) => Math.pow(Math.sin(2 * t), 2) + Math.cos(4 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "family-swap"],
    params: {},
  },
  {
    id: "star-burst",
    name: "Star burst",
    family: "exotic",
    expression: "r = 2 + cos(6θ)·sin(3θ)",
    rFunc: (t) => 2 + Math.cos(6 * t) * Math.sin(3 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "family-swap"],
    params: {},
  },
  {
    id: "wavy-circle",
    name: "Wavy circle",
    family: "exotic",
    expression: "r = 3 + sin(8θ)",
    rFunc: (t) => 3 + Math.sin(8 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "param-tweak"],
    params: {},
  },
  {
    id: "spiral-flower",
    name: "Spiral flower",
    family: "exotic",
    expression: "r = 1 + 0.5θ·sin(3θ)",
    rFunc: (t) => 1 + 0.5 * t * Math.sin(3 * t),
    thetaRange: [0, FOUR_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "family-swap"],
    params: {},
  },
  {
    id: "sunflower",
    name: "Sunflower",
    family: "exotic",
    expression: "r = 4 + 2sin(12θ)",
    rFunc: (t) => 4 + 2 * Math.sin(12 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "param-tweak"],
    params: {},
  },

  // ===== 94–100. MORE EXOTIC =====
  {
    id: "maurer-inspired",
    name: "Twisted rose",
    family: "exotic",
    expression: "r = sin(4θ)·cos(2θ) + cos(θ)",
    rFunc: (t) => Math.sin(4 * t) * Math.cos(2 * t) + Math.cos(t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "family-swap"],
    params: {},
  },
  {
    id: "crinkle",
    name: "Crinkle curve",
    family: "exotic",
    expression: "r = 1 + sin(θ)·cos(5θ)",
    rFunc: (t) => 1 + Math.sin(t) * Math.cos(5 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "family-swap"],
    params: {},
  },
  {
    id: "propeller",
    name: "Propeller",
    family: "exotic",
    expression: "r = cos(3θ)·cos(θ) + sin(2θ)",
    rFunc: (t) => Math.cos(3 * t) * Math.cos(t) + Math.sin(2 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "family-swap"],
    params: {},
  },
  {
    id: "atom",
    name: "Atom curve",
    family: "exotic",
    expression: "r = sin(3θ) + sin²(θ)",
    rFunc: (t) => Math.sin(3 * t) + Math.pow(Math.sin(t), 2),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "family-swap"],
    params: {},
  },
  {
    id: "gear",
    name: "Gear curve",
    family: "exotic",
    expression: "r = 3 + 0.5cos(16θ)",
    rFunc: (t) => 3 + 0.5 * Math.cos(16 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "param-tweak"],
    params: {},
  },
  {
    id: "nautilus",
    name: "Nautilus",
    family: "exotic",
    expression: "r = e^(0.15θ)·|sin(2θ)|",
    rFunc: (t) => Math.exp(0.15 * t) * Math.abs(Math.sin(2 * t)),
    thetaRange: [0, FOUR_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "family-swap"],
    params: {},
  },
  {
    id: "splash",
    name: "Splash",
    family: "exotic",
    expression: "r = 2cos(θ) + cos(2θ) + cos(5θ)/2",
    rFunc: (t) => 2 * Math.cos(t) + Math.cos(2 * t) + Math.cos(5 * t) / 2,
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "family-swap"],
    params: {},
  },
  {
    id: "starburst-12",
    name: "Starburst 12-pointed",
    family: "exotic",
    expression: "r = 2 + sin(6θ)² + cos(6θ)",
    rFunc: (t) => 2 + Math.pow(Math.sin(6 * t), 2) + Math.cos(6 * t),
    thetaRange: [0, TWO_PI],
    tier: 1,
    distractorStrategies: ["frequency-shift", "family-swap"],
    params: {},
  },
];

// ---------------------------------------------------------------------------
// Helper functions
// ---------------------------------------------------------------------------

export function getCurvesByTier(_tier: Tier): CurveTemplate[] {
  // No tiers — always return all curves
  return curves;
}

export function getCurvesByFamily(family: string): CurveTemplate[] {
  return curves.filter((c) => c.family === family);
}
